export default [
  {
    chapterName: 'Measure Theory',
    notations: [],
    statements: [
      {
        statementName: "$\\sigma$-field",
        type: "definition",
        content: `A $\\sigma$-field $\\mathcal{F}$ on a set $\\Omega$ is a collection of subsets of $\\Omega$ such that
                  <br/> 
                    1) $\\Omega\\in\\mathcal{F}$,
                  <br/>
                    2) $A\\in\\mathcal{F}$ implies $A^c\\in\\mathcal{F}$,
                  <br/>
                    3) $\\{A_n\\}_{n=1}^{\\infty}\\subset\\mathcal{F}$ implies $\\cup_{n=1}^{\\infty}A_n\\in\\mathcal{F}$.
                  `
        ,
        dependants: [],
        implications: [

          {
            statementName: "",
            type: "example",
            content: "The Borel $\\sigma$-field on $\\mathbb{R}$, denoted by $\\mathcal{B}(\\mathbb{R})$ is the $\\sigma$-field generated by open subsets of $\\mathbb{R}$.",
            dependants: [],
          },
        ]
      },
    ]
  }
] as Chapter[]