export default
  [
    // {
    //   name: "Metric space",
    //   key: "metric-space",
    //   type: "definition",
    //   content: ""
    // },
    // {
    //   name: "Dense subset of a metric space",
    //   key: "dense-subset-of-a-metric-space",
    //   type: "definition",
    //   parents: [
    //     {
    //       key: "metric-space"
    //     }
    //   ],
    //   content: "Let $(M,d)$ be a metric space. A subset $N$ of $M$ is said to be dense if every ball $B(x,r)\\subset M$, we have\n      $$B(x,r)\\cap N \\neq \\varnothing.$$."
    // },
    // {
    //   name: "Lipschitz continuity",
    //   key: "lipschitz-continuity",
    //   type: "definition",
    //   parents: [
    //     {
    //       key: "metric-space"
    //     }
    //   ],
    //   content: ""
    // },
    {
      name: "$\\sigma$-algebra",
      key: "sigma-algebra",
      type: "definition",
      content: "A collection of subsets of $\\Omega$ such that\n                  <br/> \n                    1) $\\Omega\\in\\F$\n                  <br/>\n                    2) $A\\in\\F$ implies $A^c\\in\\F$\n                  <br/>\n                    3) $\\{A_n\\}_{n\\in\\NN}\\subset\\F$ implies $\\cup_{n=1}^{\\infty}A_n\\in\\F$\n                  <br/>\n                  The doublet $(\\Omega,\\F)$ is called a measurable space.\n                  "
    },
    {
      name: "Generated $\\sigma$-algebra",
      key: "generated-sigma-algebra",
      type: "definition-theorem",
      parents: [
        {
          key: "sigma-algebra"
        }
      ],
      content: "Let $\\C$ be a collection of subsets of $\\Omega$. Then \n      $$\\sigma(\\C) = \\bigcap \\{ \\F : \\F \\text{ is a $\\sigma$-algebra and } \\C\\subset\\F \\}$$\n      is the smallest $\\sigma$-algebra containing $\\C$, called the $\\sigma$-algebra generated by $\\C$"
    },
    {
      name: "Borel $\\sigma$-algebra",
      key: "borel-sigma-algebra",
      type: "definition",
      parents: [
        {
          key: "sigma-algebra"
        }
      ],
    },
    {
      name: "Measurable space",
      key: "measurable-space",
      type: "definition",
      parents: [
        {
          key: "sigma-algebra"
        }
      ],
      content: "Let $\\F$ be a $\\sigma$-algebra on $\\Omega$. The doublet $(\\Omega,\\F)$ is called a measurable space."
    },
    {
      name: "Measurable function",
      key: "measurable-function",
      type: "definition",
      parents: [
        {
          key: "measurable-space"
        }
      ],
    },
    {
      name: "Measure",
      type: "definition",
      key: "measure",
      parents: [{
        key: "measurable-space"
      }
      ],
      content: "Let $(\\Omega,\\F)$ be a measurable space. A measure is a function $\\mu:\\F\\to[0,\\infty]$ such that\n                  </br>\n                  1) $\\mu(\\varnothing) = 0$\n                  </br>\n                  2) ($\\sigma$-additivity) For every family $\\{A_i\\}_{i\\in\\N}$ of disjoint measurable subsets, we have\n                  $$\\mu\\left(\\bigcup\\limits_{i=1}^\\infty A_i\\right) = \\sum\\limits_{i=1}^\\infty \\mu(A_i).$$"
    },
    {
      name: "Measure space",
      type: "definition",
      key: "measure-space",
      parents: [{
        key: 'measure'
      }],
      content: "Let $\\mu$ be a measure on a measurable space $(\\Omega,\\F)$. The triplet $(\\Omega,\\F, \\mu)$ is called a measure space"
    },
    {
      name: "Almost everywhere",
      key: "almost-everywhere",
      type: "definition",
      parents: [{
        key: 'measure-space'
      }],
      content: "Let $(\\Omega, \\F, \\mu)$ be a measure space. A property $\\P:\\Omega\\to\\{\\mathrm{true},\\mathrm{false}\\}$ is said to hold almost everywhere with respect to $\\mu$, abbreviated by $\\mu$-a.e. if\n                $$\\mu\\left(\\left\\{x\\in\\Omega : \\neg \\P(x)\\right\\}\\right) = 0.$$"
    },

    {
      name: "Lebesgue integral",
      type: "definition-theorem",
      key: "lebesgue-integral",
      parents: [
        {
          key: 'measure-space'
        },
        {
          key: 'measurable-function'
        }]
    },
    {
      name: "$L^p$ space",
      key: "lp-space",
      type: "definition-theorem",
      parents: [
        {
          key: "lebesgue-integral"
        }]
    },
    {
      name: "Probability measure",
      key: "probability-measure",
      type: "definition",
      parents: [{
        key: "measure"
      }],
      content: "A measure $\\PP$ on $(\\Omega, \\F)$ is a probability measure if $\\PP(\\Omega)$ = 1."
    },
    {
      name: "Conditional probability",
      key: "conditional-probability",
      type: "definition",
      parents: [{
        key: "probability-measure"
      }
      ],
      content: "A measure $\\PP$ on $(\\Omega, \\F)$ is a probability measure if $\\PP(\\Omega)$ = 1."
    },
    {
      name: "Measure kernel",
      key: "measure-kernel",
      type: "definition",
      parents: [
        {
          key: 'measurable-space'
        },
        {
          key: 'measurable-function'
        }],
      content: "Let $(\\Omega, \\F)$ and $(\\Gamma, \\G)$ be measurable spaces. A function $\\kappa: (\\Omega,\\G) \\to [0,\\infty]$ is a measure kernel if  $$$$ 1) For each $B\\in\\G$, $\\omega \\mapsto \\kappa(\\omega,B)$ is $(\\F\\to\\B([0,\\infty]))$-measurable $$$$ 2) For each $\\omega\\in\\Omega$, $B \\mapsto \\kappa(\\omega,B)$ is a measure on $\\G$. For a measurable function $f: \\Gamma\\to\\RR$, we write the integral of $f$ with respect to $\\kappa(\\omega,B)$ as $\\int f(y)\\d\\kappa(\\omega,y) := \\int f(y)\\kappa(\\omega,\\d y)$ $$$$   If $(\\Omega, \\F) = (\\Gamma, \\G)$, we call $\\kappa$ a measure kernel on $(\\Omega, \\F)$."
    },
    {
      name: "Product of kernels",
      type: "definition",
      key: "product-of-kernels",
      parents: [
        { key: "measure-kernel" }
      ],
      content: "Let $\\kappa, \\lambda$ be measure kernels on $(\\Omega, \\F)$. The product of $\\kappa$ and $\\lambda$ is a measure kernel on $(\\Omega, \\F)$, defined by\n      $$(\\kappa\\lambda)(x,B) = \\int\\kappa(x,\\dy)\\lambda(y, B).$$"
    },
    {
      name: "Probability kernel",
      key: "probability-kernel",
      type: "definition",
      parents: [
        {
          key: "measure-kernel",
          relation: 'specializes'
        }
      ],
    },
    {
      name: "Probability space",
      type: "definition",
      key: "probability-space",
      parents: [{
        key: 'measure-space'
      }],
      content: "A measure space $(\\Omega, \\F, \\PP)$ is a probability space if $\\PP$ is a probability measure. In such case, each element of $\\Omega$ is called an outcome and each element of $\\F$ is called an event."
    },
    {
      name: "Random variable",
      key: "random-variable",
      type: "definition",
      parents: [{
        key: 'probability-space'
      },
      {
        key: 'measurable-function'
      }],
      content: "Let $(\\Omega, \\F, \\PP)$ be a probability space. A function $X : \\Omega\\to\\RR^d$ is called a random variable if $X$ is $(\\F\\to\\B(\\RR^d))$-measurable. We will write $\\B_X := \\B(\\RR^d))$, the Borel $\\sigma$-algebra associated to $X$."
    },
    {
      name: "Distribution",
      key: "distribution",
      type: "definition-theorem",
      parents: [
        { key: 'random-variable' }
      ],
      content: "Let $(\\Omega, \\F, \\PP)$ be a probability space and $X$ be a $d$-dimensional random variable. Then $X$ induces a measure $\\PP_X(B) : \\B(\\RR^d) \\to \\R$ such that \n      $$\\PP_X(B) = \\PP(X^{-1}(B)),$$ called the distribution or the law of $X$."
    },
    {
      name: "Expectation",
      key: "expectation of a random variable",
      type: "definition",
      parents: [
        {
          key: 'random-variable'
        }
      ]
    },
    {
      name: "Stochastic process",
      key: "stochastic-process",
      type: "definition",
      parents: [
        {
          key: 'random-variable'
        }
      ],
      content: "Let $T$ be an index set. A stochastic process is a collection of random variables $\\{X_t\\}_{t\\in T}$, where $$X_t: \\Omega\\to\\RR^d.$$ We consider $T=\\NN$ equipped with the $\\sigma$-algebra $\\T = 2^T$ or $T=\\RR_+$ equipped with $\\T = \\B(\\RR_+)$. The tuple $(T,\\T)$ is called the time space, the tuple $(\\RR^d,\\B(\\RR^d))$ is called the state space."
    },
    {
      name: "Adapted stochastic process",
      key: "adapted-stochastic-process",
      type: "definition",
      parents: [{
        key: "stochastic-process"
      }],
      content: "Let $(\\Omega, \\F, \\PP)$ be a probability space and $X := \\{X_t\\}_{t\\in T}$ be a stochastic process. Let $\\{\\F_t\\}$ be an increasing class of sub-$\\sigma$-algebras of $\\FF$, called a filtration. The process $X$ is said to be adapted to $\\{\\F_t\\}$ if $X_t$ is $\\F_t$-measurable, for every $t\\in T$."
    },
    {
      name: "Jointly measurable stochastic process",
      key: "jointly-measurable-stochastic-process",
      type: "definition",
      parents: [{
        key: "stochastic-process"
      }],
      content: "A stochastic process $X$ with probability space $(\\Omega,\\F,\\PP)$ time space $(T, \\T)$, state space $(\\RR^d, \\B(\\RR^d))$ is jointly measurable if X is $(\\T\\otimes \\F \\to \\B(\\RR^d))$-measurable."
    },
    {
      name: "Wiener process",
      key: "wiener-process",
      type: "definition-theorem",
      parents: [{
        key: "stochastic-process"
      }],
    },
    {
      name: "Markov process",
      type: "definition",
      key: "markov-process",
      parents: [{
        key: "stochastic-process"
      }],
    },
    {
      name: "Progressively measurable process",
      key: "progressively-measurable-process",
      type: "definition",
      content: "",
      parents: [{
        key: "adapted-stochastic-process"
      }],
    },
    {
      name: "Diffusion",
      key: "diffusion",
      type: "definition",
      content: "A stochastic process $X$ adapted to a filtration $\\F$ is a diffusion when it is a strong Markov process with respect to $\\F$, homogeneous in time, and has continuous sample paths.",
      parents: [{
        key: "adapted-stochastic-process"
      }],
    },
  ] as Vertex[]
